version: "3.0"
services:
  app:
    build: ./docker/app
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/app/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/app/apache/logs:/var/log/apache2/
    links:
      - mysql:mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=mvc_db
